{
  "id": "CVE-2023-5002",
  "sourceIdentifier": "patrick@puiterwijk.org",
  "published": "2023-09-22T14:15:47.213",
  "lastModified": "2023-09-22T14:15:47.213",
  "vulnStatus": "Received",
  "descriptions": [
    {
      "lang": "en",
      "value": "A flaw was found in pgAdmin. This issue occurs when the pgAdmin server HTTP API validates the path a user selects to external PostgreSQL utilities such as pg_dump and pg_restore. Versions of pgAdmin prior to 7.6 failed to properly control the server code executed on this API, allowing an authenticated user to run arbitrary commands on the server."
    }
  ],
  "metrics": {
    "cvssMetricV31": [
      {
        "source": "patrick@puiterwijk.org",
        "type": "Secondary",
        "cvssData": {
          "version": "3.1",
          "vectorString": "CVSS:3.1/AV:N/AC:H/PR:H/UI:R/S:U/C:L/I:H/A:H",
          "attackVector": "NETWORK",
          "attackComplexity": "HIGH",
          "privilegesRequired": "HIGH",
          "userInteraction": "REQUIRED",
          "scope": "UNCHANGED",
          "confidentialityImpact": "LOW",
          "integrityImpact": "HIGH",
          "availabilityImpact": "HIGH",
          "baseScore": 6.0,
          "baseSeverity": "MEDIUM"
        },
        "exploitabilityScore": 0.5,
        "impactScore": 5.5
      }
    ]
  },
  "references": [
    {
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2239164",
      "source": "patrick@puiterwijk.org"
    },
    {
      "url": "https://github.com/pgadmin-org/pgadmin4/issues/6763",
      "source": "patrick@puiterwijk.org"
    }
  ]
}