{
  "id": "CVE-2020-27545",
  "sourceIdentifier": "cve@mitre.org",
  "published": "2023-04-16T00:15:07.273",
  "lastModified": "2023-04-17T13:12:43.170",
  "vulnStatus": "Awaiting Analysis",
  "descriptions": [
    {
      "lang": "en",
      "value": "libdwarf before 20201017 has a one-byte out-of-bounds read because of an invalid pointer dereference via an invalid line table in a crafted object."
    }
  ],
  "metrics": {},
  "references": [
    {
      "url": "http://web.archive.org/web/20190601140703/https://sourceforge.net/projects/libdwarf/",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2025694",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://github.com/davea42/libdwarf-code/commit/95f634808c01f1c61bbec56ed2395af997f397ea",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://sourceforge.net/projects/libdwarf/",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://www.prevanders.net/dwarfbug.html#DW202010-001",
      "source": "cve@mitre.org"
    }
  ]
}