{
  "id": "CVE-2006-1542",
  "sourceIdentifier": "cve@mitre.org",
  "published": "2006-03-30T11:02:00.000",
  "lastModified": "2017-10-19T01:29:04.627",
  "vulnStatus": "Modified",
  "evaluatorSolution": "Successful exploitation requires that the Python is running on Linux 2.6.12.5 under gcc 4.0.3 with libc 2.3.5",
  "descriptions": [
    {
      "lang": "en",
      "value": "Stack-based buffer overflow in Python 2.4.2 and earlier, running on Linux 2.6.12.5 under gcc 4.0.3 with libc 2.3.5, allows local users to cause a \"stack overflow,\" and possibly gain privileges, by running a script from a current working directory that has a long name, related to the realpath function.  NOTE: this might not be a vulnerability. However, the fact that it appears in a programming language interpreter could mean that some applications are affected, although attack scenarios might be limited because the attacker might already need to cross privilege boundaries to cause an exploitable program to be placed in a directory with a long name; or, depending on the method that Python uses to determine the current working directory, setuid applications might be affected."
    }
  ],
  "vendorComments": [
    {
      "organization": "Red Hat",
      "comment": "Red Hat is aware of this issue and is tracking it via the following bug:\nhttps://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=187900\n\nThe Red Hat Security Response Team has rated this issue as having low security impact, a future update may address this flaw.  More information regarding issue severity can be found here:\nhttp://www.redhat.com/security/updates/classification/\n\nRed Hat Enterprise Linux 5 is not vulnerable to this issue as it contains a backported patch.",
      "lastModified": "2007-03-14T00:00:00"
    }
  ],
  "metrics": {
    "cvssMetricV2": [
      {
        "source": "nvd@nist.gov",
        "type": "Primary",
        "cvssData": {
          "version": "2.0",
          "vectorString": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
          "accessVector": "LOCAL",
          "accessComplexity": "HIGH",
          "authentication": "NONE",
          "confidentialityImpact": "PARTIAL",
          "integrityImpact": "PARTIAL",
          "availabilityImpact": "PARTIAL",
          "baseScore": 3.7
        },
        "baseSeverity": "LOW",
        "exploitabilityScore": 1.9,
        "impactScore": 6.4,
        "acInsufInfo": false,
        "obtainAllPrivilege": false,
        "obtainUserPrivilege": false,
        "obtainOtherPrivilege": true,
        "userInteractionRequired": false
      }
    ]
  },
  "weaknesses": [
    {
      "source": "nvd@nist.gov",
      "type": "Primary",
      "description": [
        {
          "lang": "en",
          "value": "NVD-CWE-Other"
        }
      ]
    }
  ],
  "configurations": [
    {
      "nodes": [
        {
          "operator": "OR",
          "negate": false,
          "cpeMatch": [
            {
              "vulnerable": true,
              "criteria": "cpe:2.3:a:python_software_foundation:python:*:*:*:*:*:*:*:*",
              "versionEndIncluding": "2.4.2",
              "matchCriteriaId": "D47C1A7E-146E-4C1F-9E1B-67948DA4F9BA"
            },
            {
              "vulnerable": true,
              "criteria": "cpe:2.3:a:python_software_foundation:python:2.2:*:*:*:*:*:*:*",
              "matchCriteriaId": "5F19339B-AAA0-4042-895C-4A21C051285C"
            },
            {
              "vulnerable": true,
              "criteria": "cpe:2.3:a:python_software_foundation:python:2.2.1:*:*:*:*:*:*:*",
              "matchCriteriaId": "08050FA1-95FB-4308-A6C2-622591C79BEE"
            },
            {
              "vulnerable": true,
              "criteria": "cpe:2.3:a:python_software_foundation:python:2.3:*:*:*:*:*:*:*",
              "matchCriteriaId": "E0807131-7BF9-475F-B42B-25EFD46A96BA"
            },
            {
              "vulnerable": true,
              "criteria": "cpe:2.3:a:python_software_foundation:python:2.3.1:*:*:*:*:*:*:*",
              "matchCriteriaId": "080ED7C9-3348-49D8-937D-83A0D629374B"
            },
            {
              "vulnerable": true,
              "criteria": "cpe:2.3:a:python_software_foundation:python:2.3.2:*:*:*:*:*:*:*",
              "matchCriteriaId": "11523A7B-F557-4E74-B892-5F7D05FE973F"
            },
            {
              "vulnerable": true,
              "criteria": "cpe:2.3:a:python_software_foundation:python:2.3.3:*:*:*:*:*:*:*",
              "matchCriteriaId": "A3945EBB-D386-4995-BF95-A7AC5E163E1C"
            },
            {
              "vulnerable": true,
              "criteria": "cpe:2.3:a:python_software_foundation:python:2.3.4:*:*:*:*:*:*:*",
              "matchCriteriaId": "DE249685-99F0-4ECB-A2E9-F3E306D87E02"
            },
            {
              "vulnerable": true,
              "criteria": "cpe:2.3:a:python_software_foundation:python:2.4:*:*:*:*:*:*:*",
              "matchCriteriaId": "A9AFAD75-1916-44AC-825C-47F8BDC3A8F4"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "url": "http://www.gotfault.net/research/exploit/gexp-python.py",
      "source": "cve@mitre.org",
      "tags": [
        "Exploit"
      ]
    },
    {
      "url": "http://www.redhat.com/support/errata/RHSA-2008-0629.html",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://www.exploit-db.com/exploits/1591",
      "source": "cve@mitre.org"
    }
  ]
}