{
  "id": "CVE-2023-41164",
  "sourceIdentifier": "cve@mitre.org",
  "published": "2023-11-03T05:15:29.447",
  "lastModified": "2023-11-03T05:15:29.447",
  "vulnStatus": "Received",
  "descriptions": [
    {
      "lang": "en",
      "value": "In Django 3.2 before 3.2.21, 4.1 before 4.1.11, and 4.2 before 4.2.5, django.utils.encoding.uri_to_iri() is subject to a potential DoS (denial of service) attack via certain inputs with a very large number of Unicode characters."
    }
  ],
  "metrics": {},
  "references": [
    {
      "url": "https://docs.djangoproject.com/en/4.2/releases/security/",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://groups.google.com/forum/#!forum/django-announce",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://www.djangoproject.com/weblog/2023/sep/04/security-releases/",
      "source": "cve@mitre.org"
    }
  ]
}