{
  "id": "CVE-2023-41105",
  "sourceIdentifier": "cve@mitre.org",
  "published": "2023-08-23T07:15:08.590",
  "lastModified": "2023-08-25T01:15:09.277",
  "vulnStatus": "Awaiting Analysis",
  "descriptions": [
    {
      "lang": "en",
      "value": "An issue was discovered in Python 3.11 through 3.11.4. If a path containing '\\0' bytes is passed to os.path.normpath(), the path will be truncated unexpectedly at the first '\\0' byte. There are plausible cases in which an application would have rejected a filename for security reasons in Python 3.10.x or earlier, but that filename is no longer rejected in Python 3.11.x."
    }
  ],
  "metrics": {},
  "references": [
    {
      "url": "https://github.com/python/cpython/issues/106242",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://github.com/python/cpython/pull/107981",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://github.com/python/cpython/pull/107982",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://github.com/python/cpython/pull/107983",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/D6CDW3ZZC5D444YGL3VQUY6D4ECMCQLD/",
      "source": "cve@mitre.org"
    }
  ]
}