{
  "id": "CVE-2023-39661",
  "sourceIdentifier": "cve@mitre.org",
  "published": "2023-08-15T17:15:13.133",
  "lastModified": "2023-08-15T17:15:41.713",
  "vulnStatus": "Awaiting Analysis",
  "descriptions": [
    {
      "lang": "en",
      "value": "An issue in pandas-ai v.0.9.1 and before allows a remote attacker to execute arbitrary code via the _is_jailbreak function."
    }
  ],
  "metrics": {},
  "references": [
    {
      "url": "https://github.com/gventuri/pandas-ai/issues/410",
      "source": "cve@mitre.org"
    }
  ]
}