{
  "id": "CVE-2004-0150",
  "sourceIdentifier": "cve@mitre.org",
  "published": "2004-04-15T04:00:00.000",
  "lastModified": "2017-10-10T01:30:18.297",
  "vulnStatus": "Modified",
  "descriptions": [
    {
      "lang": "en",
      "value": "Buffer overflow in the getaddrinfo function in Python 2.2 before 2.2.2, when IPv6 support is disabled, allows remote attackers to execute arbitrary code via an IPv6 address that is obtained using DNS."
    },
    {
      "lang": "es",
      "value": "Desbordamiento de b\u00fafer en getaddrinfo de Python 2.2 permite a atacantes remotos ejecutar c\u00f3digo arbitrario mediante una direcci\u00f3n IPv6 obtenida usando DNS."
    }
  ],
  "metrics": {
    "cvssMetricV2": [
      {
        "source": "nvd@nist.gov",
        "type": "Primary",
        "cvssData": {
          "version": "2.0",
          "vectorString": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
          "accessVector": "NETWORK",
          "accessComplexity": "LOW",
          "authentication": "NONE",
          "confidentialityImpact": "PARTIAL",
          "integrityImpact": "PARTIAL",
          "availabilityImpact": "PARTIAL",
          "baseScore": 7.5
        },
        "baseSeverity": "HIGH",
        "exploitabilityScore": 10.0,
        "impactScore": 6.4,
        "acInsufInfo": false,
        "obtainAllPrivilege": false,
        "obtainUserPrivilege": false,
        "obtainOtherPrivilege": true,
        "userInteractionRequired": false
      }
    ]
  },
  "weaknesses": [
    {
      "source": "nvd@nist.gov",
      "type": "Primary",
      "description": [
        {
          "lang": "en",
          "value": "NVD-CWE-Other"
        }
      ]
    }
  ],
  "configurations": [
    {
      "nodes": [
        {
          "operator": "OR",
          "negate": false,
          "cpeMatch": [
            {
              "vulnerable": true,
              "criteria": "cpe:2.3:a:python_software_foundation:python:2.2:*:*:*:*:*:*:*",
              "matchCriteriaId": "5F19339B-AAA0-4042-895C-4A21C051285C"
            },
            {
              "vulnerable": true,
              "criteria": "cpe:2.3:a:python_software_foundation:python:2.2.1:*:*:*:*:*:*:*",
              "matchCriteriaId": "08050FA1-95FB-4308-A6C2-622591C79BEE"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "url": "http://www.debian.org/security/2004/dsa-458",
      "source": "cve@mitre.org",
      "tags": [
        "Patch",
        "Vendor Advisory"
      ]
    },
    {
      "url": "http://www.gentoo.org/security/en/glsa/glsa-200409-03.xml",
      "source": "cve@mitre.org"
    },
    {
      "url": "http://www.mandrakesoft.com/security/advisories?name=MDKSA-2004:019",
      "source": "cve@mitre.org"
    },
    {
      "url": "http://www.securityfocus.com/bid/9836",
      "source": "cve@mitre.org",
      "tags": [
        "Patch",
        "Vendor Advisory"
      ]
    },
    {
      "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/15409",
      "source": "cve@mitre.org"
    }
  ]
}