{
  "id": "CVE-2022-48565",
  "sourceIdentifier": "cve@mitre.org",
  "published": "2023-08-22T19:16:32.007",
  "lastModified": "2023-08-22T20:10:36.537",
  "vulnStatus": "Awaiting Analysis",
  "descriptions": [
    {
      "lang": "en",
      "value": "An XML External Entity (XXE) issue was discovered in Python through 3.9.1. The plistlib module no longer accepts entity declarations in XML plist files to avoid XML vulnerabilities."
    }
  ],
  "metrics": {},
  "references": [
    {
      "url": "https://bugs.python.org/issue42051",
      "source": "cve@mitre.org"
    }
  ]
}